/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package finalproject_mari_kanepaul;
import javax.swing.BorderFactory;
import java.awt.Color;
/**
 *
 * @author Kane
 */
public class BookCardComponent extends javax.swing.JPanel {

    /**
     * Creates new form BookCardComponent
     */
    public BookCardComponent() {
        initComponents();
        styleCard();
    }
    
    public void setBookData(String title, String author, String isbn, String shelf,
        boolean checkedOut, String borrower, String dueDate) {

    titleLabel.setText(title);
    authorLabel.setText("by " + author);
    isbnLabel.setText("ISBN: " + isbn);
    shelfLabel.setText("Shelf: " + shelf);

    if (checkedOut) {
        statusLabel.setText("Checked Out");
        statusLabel.setBackground(new java.awt.Color(239, 108, 0));

        actionButton.setText("CHECK IN");
        actionButton.setBackground(new java.awt.Color(46, 125, 50));

        borrowerLabel.setText("Borrowed by: " + borrower);
        dueLabel.setText("Due: " + dueDate);
        borrowerLabel.setVisible(true);
        dueLabel.setVisible(true);
    } else {
        statusLabel.setText("Available");
        statusLabel.setBackground(new java.awt.Color(46, 125, 50));

        actionButton.setText("CHECK OUT");
        actionButton.setBackground(new java.awt.Color(25, 118, 210));

        borrowerLabel.setVisible(false);
        dueLabel.setVisible(false);
    }
}
    
    private void styleCard() {
    putClientProperty("FlatLaf.style", "arc: 12");

    statusLabel.putClientProperty("FlatLaf.style", "arc: 999");
    statusLabel.setBorder(BorderFactory.createEmptyBorder(4, 10, 4, 10));

    actionButton.putClientProperty("JButton.arc", 8);
    actionButton.setBackground(new Color(25, 118, 210));
    actionButton.setForeground(Color.WHITE);

    jButton1.setText("\u22EE");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        topPanel = new javax.swing.JPanel();
        statusLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        detailsPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        authorLabel = new javax.swing.JLabel();
        isbnLabel = new javax.swing.JLabel();
        shelfLabel = new javax.swing.JLabel();
        borrowerLabel = new javax.swing.JLabel();
        dueLabel = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        actionButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        setPreferredSize(new java.awt.Dimension(275, 390));
        setLayout(new java.awt.BorderLayout());

        topPanel.setBackground(new java.awt.Color(255, 255, 255));
        topPanel.setPreferredSize(new java.awt.Dimension(347, 50));

        statusLabel.setBackground(new java.awt.Color(46, 125, 50));
        statusLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        statusLabel.setForeground(new java.awt.Color(255, 255, 255));
        statusLabel.setText("Available");
        statusLabel.setOpaque(true);

        jButton1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("⋮");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(statusLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusLabel)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(topPanel, java.awt.BorderLayout.NORTH);

        detailsPanel.setBackground(new java.awt.Color(255, 255, 255));

        titleLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 0, 0));
        titleLabel.setText("To Kill a Mockingbird");

        authorLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        authorLabel.setText("by Harper Lee");

        isbnLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        isbnLabel.setText("ISBN: 978-0-06-112008-4");

        shelfLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        shelfLabel.setText("Shelf: A-12");

        borrowerLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        borrowerLabel.setText("Borrowed by: John Smith");

        dueLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        dueLabel.setText("Due: 6/5/2026");

        javax.swing.GroupLayout detailsPanelLayout = new javax.swing.GroupLayout(detailsPanel);
        detailsPanel.setLayout(detailsPanelLayout);
        detailsPanelLayout.setHorizontalGroup(
            detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailsPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dueLabel)
                    .addComponent(borrowerLabel)
                    .addComponent(shelfLabel)
                    .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(authorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isbnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        detailsPanelLayout.setVerticalGroup(
            detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(authorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(isbnLabel)
                .addGap(46, 46, 46)
                .addComponent(shelfLabel)
                .addGap(18, 18, 18)
                .addComponent(borrowerLabel)
                .addGap(18, 18, 18)
                .addComponent(dueLabel)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        add(detailsPanel, java.awt.BorderLayout.CENTER);

        buttonPanel.setBackground(new java.awt.Color(255, 255, 255));
        buttonPanel.setPreferredSize(new java.awt.Dimension(347, 60));
        buttonPanel.setLayout(new java.awt.GridBagLayout());

        actionButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        actionButton.setText("Check Out");
        actionButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        actionButton.setPreferredSize(new java.awt.Dimension(180, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 15, 15);
        buttonPanel.add(actionButton, gridBagConstraints);

        add(buttonPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actionButton;
    private javax.swing.JLabel authorLabel;
    private javax.swing.JLabel borrowerLabel;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel detailsPanel;
    private javax.swing.JLabel dueLabel;
    private javax.swing.JLabel isbnLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel shelfLabel;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
