/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalproject_mari_kanepaul;

import java.awt.Font;
import java.awt.event.ComponentAdapter;
import javax.swing.JButton;
import javax.swing.JLayeredPane;

/**
 *
 * @author Kane
 */
public class MainDashboard extends javax.swing.JFrame {
    
    private JButton floatingButton;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainDashboard.class.getName());

    /**
     * Creates new form MainDashboard
     */
    public MainDashboard() {
        initComponents();
        styleDashboard();
        loadBookCards();
        initFloatingButton();
    }
    
    private void initFloatingButton() {
   
    floatingButton = new javax.swing.JButton("+");
    floatingButton.setFont(new java.awt.Font("SansSerif", Font.PLAIN, 28));
    floatingButton.setBackground(new java.awt.Color(25, 118, 210)); // Primary Blue
    floatingButton.setForeground(java.awt.Color.WHITE);
    floatingButton.setFocusPainted(false);
    floatingButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    floatingButton.putClientProperty("JButton.arc", 999); 
    int buttonSize = 56;
    floatingButton.setSize(buttonSize, buttonSize);
    JLayeredPane layeredPane = getLayeredPane();
    layeredPane.add(floatingButton, javax.swing.JLayeredPane.PALETTE_LAYER);
    
    this.addComponentListener(new ComponentAdapter() {
        @Override
        public void componentResized(java.awt.event.ComponentEvent e) {
            positionFloatingButton();
        }
    });
    positionFloatingButton();
    floatingButton.addActionListener(e -> {
        AddBookDialog dialog = new AddBookDialog(this, true);
    dialog.setVisible(true);
    });
}

private void positionFloatingButton() {
    if (floatingButton == null) return;
    
    JLayeredPane layeredPane = getLayeredPane();
    
    
    int padding = 28; 
    
    int x = layeredPane.getWidth() - floatingButton.getWidth() - padding;
    int y = layeredPane.getHeight() - floatingButton.getHeight() - padding;
    
    floatingButton.setLocation(x, y);
} 
    
    private void styleDashboard() {
    searchBar.putClientProperty("JTextField.arc", 12);
    jComboBox1.putClientProperty("JComponent.roundRect", true);
    jComboBox2.putClientProperty("JComponent.roundRect", true);
    booksGridPanel.setBackground(new java.awt.Color(250, 250, 250));
    searchBar.putClientProperty("JTextField.placeholderText", "Search by title, author, ISBN");
    searchBar.putClientProperty("JTextField.showClearButton", true);
    totalBooksCard.putClientProperty("FlatLaf.style", "arc: 12");
    availableCard.putClientProperty("FlatLaf.style", "arc: 12");
    checkedOutCard.putClientProperty("FlatLaf.style", "arc: 12");
}
    
    private void loadBookCards() {
    
    booksGridPanel.removeAll();
    BooksDAO booksDAO = new BooksDAO();
    jLabel3.setText(String.valueOf(booksDAO.countAllCopies()));
    jLabel5.setText(String.valueOf(booksDAO.countAvailableCopies()));
    jLabel7.setText(String.valueOf(booksDAO.countCheckedOutCopies()));

    for (Object[] row : booksDAO.getBookCards()) {
        String title = (String) row[1];
        String author = (String) row[2];
        String isbn = (String) row[3];
        String shelf = row[4] == null ? "No Shelf" : (String) row[4];
        String status = (String) row[5];
        String borrower = row[6] == null ? "" : (String) row[6];
        String dueDate = row[7] == null ? "" : row[7].toString();

        boolean checkedOut = "Checked Out".equalsIgnoreCase(status);

        BookCardComponent card = new BookCardComponent();
        card.setBookData(
                title,
                author,
                isbn,
                shelf,
                checkedOut,
                borrower,
                dueDate
        );

        booksGridPanel.add(card);
    }

    booksGridPanel.revalidate();
    booksGridPanel.repaint();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        headerWrapperPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        statsPanel = new javax.swing.JPanel();
        totalBooksCard = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        availableCard = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        checkedOutCard = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        filterBarPanel = new javax.swing.JPanel();
        searchBar = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        booksGridPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headerWrapperPanel.setBackground(new java.awt.Color(250, 250, 250));
        headerWrapperPanel.setPreferredSize(new java.awt.Dimension(1000, 320));
        headerWrapperPanel.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Library Management System");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 0);
        headerWrapperPanel.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Track and manage your book collection.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 10, 0);
        headerWrapperPanel.add(jLabel2, gridBagConstraints);

        statsPanel.setOpaque(false);
        statsPanel.setPreferredSize(new java.awt.Dimension(1000, 100));
        statsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5));

        totalBooksCard.setBackground(new java.awt.Color(25, 118, 210));
        totalBooksCard.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        totalBooksCard.setMinimumSize(new java.awt.Dimension(153, 138));
        totalBooksCard.setPreferredSize(new java.awt.Dimension(123, 138));
        totalBooksCard.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("6");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        totalBooksCard.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total Books");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        totalBooksCard.add(jLabel4, gridBagConstraints);

        statsPanel.add(totalBooksCard);

        availableCard.setBackground(new java.awt.Color(46, 125, 50));
        availableCard.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        availableCard.setMinimumSize(new java.awt.Dimension(153, 138));
        availableCard.setPreferredSize(new java.awt.Dimension(103, 138));
        availableCard.setLayout(new java.awt.GridBagLayout());

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        availableCard.add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Available");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        availableCard.add(jLabel6, gridBagConstraints);

        statsPanel.add(availableCard);

        checkedOutCard.setBackground(new java.awt.Color(239, 108, 0));
        checkedOutCard.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        checkedOutCard.setMinimumSize(new java.awt.Dimension(153, 138));
        checkedOutCard.setPreferredSize(new java.awt.Dimension(133, 138));
        checkedOutCard.setLayout(new java.awt.GridBagLayout());

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        checkedOutCard.add(jLabel7, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Checked Out");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        checkedOutCard.add(jLabel8, gridBagConstraints);

        statsPanel.add(checkedOutCard);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        headerWrapperPanel.add(statsPanel, gridBagConstraints);

        filterBarPanel.setMinimumSize(new java.awt.Dimension(500, 60));
        filterBarPanel.setOpaque(false);
        filterBarPanel.setPreferredSize(new java.awt.Dimension(300, 520));
        filterBarPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 10));

        searchBar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        searchBar.setForeground(new java.awt.Color(153, 153, 153));
        searchBar.setToolTipText("");
        searchBar.setPreferredSize(new java.awt.Dimension(200, 35));
        searchBar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchBarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchBarFocusLost(evt);
            }
        });
        filterBarPanel.add(searchBar);

        jComboBox1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Books", "Available", "Checked Out" }));
        jComboBox1.setMinimumSize(new java.awt.Dimension(103, 25));
        jComboBox1.setPreferredSize(new java.awt.Dimension(100, 35));
        filterBarPanel.add(jComboBox1);

        jComboBox2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Shelves", "A-12", "B-05", "A-08", "C-14" }));
        jComboBox2.setMinimumSize(new java.awt.Dimension(91, 25));
        jComboBox2.setPreferredSize(new java.awt.Dimension(100, 35));
        filterBarPanel.add(jComboBox2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        headerWrapperPanel.add(filterBarPanel, gridBagConstraints);

        getContentPane().add(headerWrapperPanel, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setBorder(null);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(1000, 480));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1000, 480));

        booksGridPanel.setBackground(new java.awt.Color(250, 250, 250));
        booksGridPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 25, 25));
        jScrollPane1.setViewportView(booksGridPanel);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1014, 808));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchBarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchBarFocusGained

    }//GEN-LAST:event_searchBarFocusGained

    private void searchBarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchBarFocusLost

    }//GEN-LAST:event_searchBarFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel availableCard;
    private javax.swing.JPanel booksGridPanel;
    private javax.swing.JPanel checkedOutCard;
    private javax.swing.JPanel filterBarPanel;
    private javax.swing.JPanel headerWrapperPanel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField searchBar;
    private javax.swing.JPanel statsPanel;
    private javax.swing.JPanel totalBooksCard;
    // End of variables declaration//GEN-END:variables
}
